"""
ZettaBrainSkill CLI - Main entry point
"""

import typer
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
from rich.table import Table
from typing import Optional

from zettabrain_skills import __version__
from zettabrain_skills.skills.parser import load_skill
from zettabrain_skills.core.engine import GenerationEngine
from zettabrain_skills.core.models import GenerationRequest

app = typer.Typer(
    name="zettabrain-skills",
    help="ZettaBrainSkill - AI-powered document generation with skills",
    add_completion=False,
)
console = Console()


@app.command()
def version():
    """Show version information"""
    console.print(f"[bold cyan]ZettaBrainSkill[/bold cyan] version {__version__}")


@app.command()
def generate(
    skill_file: str,
    input: str = typer.Option(..., "--input", "-i"),
    output: Optional[str] = typer.Option(None, "--output", "-o"),
    temperature: Optional[float] = typer.Option(None, "--temperature", "-t"),
    max_tokens: Optional[int] = typer.Option(None, "--max-tokens", "-m"),
    business: str = typer.Option("default", "--business", "-b"),
):
    """Generate a document using a skill"""

    try:
        # Load skill
        console.print(f"[blue]📖 Loading skill from {skill_file}...[/blue]")
        skill = load_skill(skill_file)
        console.print(
            f"[green]✓[/green] Loaded skill: [bold]{skill.name}[/bold] v{skill.version}"
        )
        console.print(f"  Type: {skill.business_type}")
        console.print(f"  Temperature: {temperature or skill.temperature}")
        console.print(f"  Max tokens: {max_tokens or skill.max_tokens}")
        console.print()

        # Initialize engine
        console.print("[blue]🚀 Initializing generation engine...[/blue]")
        engine = GenerationEngine()

        # Check LLM health
        if not engine.llm_provider.check_health():
            console.print(
                "[red]✗ Ollama is not running or not accessible.[/red]\n"
                "[yellow]Start it with:[/yellow] ollama serve"
            )
            raise typer.Exit(1)

        model_info = engine.llm_provider.get_model_info()
        console.print(
            f"[green]✓[/green] Connected to {model_info.get('provider', 'LLM')} "
            f"({model_info.get('model', 'unknown')})"
        )
        console.print()

        # Generate
        console.print("[blue]⚙️  Generating document...[/blue]")
        request = GenerationRequest(
            input=input,
            skill_name=skill.name,
            business_id=business,
            temperature=temperature,
            max_tokens=max_tokens,
        )

        result = engine.generate(skill, request)

        if not result.success:
            console.print(f"[red]✗ Generation failed: {result.error}[/red]")
            raise typer.Exit(1)

        # Validate output
        is_valid, warnings = engine.validate_output(skill, result)
        if warnings:
            console.print("[yellow]⚠️  Warnings:[/yellow]")
            for warning in warnings:
                console.print(f"  - {warning}")
            console.print()

        # Display result
        console.print()
        console.print(
            Panel(
                Markdown(result.content),
                title=f"✨ Generated by {skill.name}",
                subtitle=f"Generated in {result.generation_time_ms}ms",
                border_style="green",
            )
        )
        console.print()

        # Save to file if requested
        if output:
            Path(output).write_text(result.content, encoding="utf-8")
            console.print(f"[green]✓[/green] Saved to [bold]{output}[/bold]")
        else:
            console.print(
                "[dim]Tip: Use --output/-o to save to a file[/dim]"
            )

        # Show metadata
        console.print()
        console.print("[dim]Metadata:[/dim]")
        console.print(f"  ID: {result.id}")
        console.print(f"  Generated at: {result.created_at.strftime('%Y-%m-%d %H:%M:%S')}")

    except FileNotFoundError as e:
        console.print(f"[red]✗ File not found: {e}[/red]")
        raise typer.Exit(1)
    except ValueError as e:
        console.print(f"[red]✗ Validation error: {e}[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]✗ Error: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def validate(
    skill_file: str,
):
    """Validate a skill file"""

    try:
        console.print(f"[blue]🔍 Validating skill: {skill_file}[/blue]")
        skill = load_skill(skill_file)

        console.print()
        console.print("[green]✓ Skill is valid![/green]")
        console.print()

        # Display skill info
        table = Table(title="Skill Information", show_header=False)
        table.add_column("Property", style="cyan")
        table.add_column("Value", style="white")

        table.add_row("Name", skill.name)
        table.add_row("Version", skill.version)
        table.add_row("Business Type", skill.business_type)
        table.add_row("Description", skill.description[:100] + "..." if len(skill.description) > 100 else skill.description)
        table.add_row("Requires Corpus", "Yes" if skill.requires_corpus else "No")
        table.add_row("Citation Required", "Yes" if skill.citation_required else "No")
        table.add_row("Temperature", str(skill.temperature))
        table.add_row("Max Tokens", str(skill.max_tokens))
        table.add_row("Instructions Length", f"{len(skill.instructions)} characters")

        if skill.requires_discovery:
            table.add_row(
                "Requires Discovery", ", ".join(skill.requires_discovery)
            )

        if skill.references:
            table.add_row("References", ", ".join(skill.references.keys()))

        if skill.tags:
            table.add_row("Tags", ", ".join(skill.tags))

        console.print(table)

    except FileNotFoundError:
        console.print(f"[red]✗ File not found: {skill_file}[/red]")
        raise typer.Exit(1)
    except ValueError as e:
        console.print(f"[red]✗ Invalid skill:[/red]")
        console.print(f"  {e}")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]✗ Error: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def check():
    """Check if Ollama is running and accessible"""

    console.print("[blue]🔍 Checking Ollama status...[/blue]")

    from zettabrain_skills.llm.providers.ollama import OllamaProvider

    provider = OllamaProvider()

    if provider.check_health():
        console.print("[green]✓ Ollama is running and accessible[/green]")

        model_info = provider.get_model_info()
        console.print(f"\n[cyan]Model:[/cyan] {model_info.get('model', 'unknown')}")
        console.print(f"[cyan]URL:[/cyan] {model_info.get('base_url', 'unknown')}")
    else:
        console.print("[red]✗ Ollama is not accessible[/red]")
        console.print("\n[yellow]Make sure Ollama is running:[/yellow]")
        console.print("  1. Start Ollama: ollama serve")
        console.print("  2. Pull a model: ollama pull llama3.1:8b")
        raise typer.Exit(1)


if __name__ == "__main__":
    app()
